name: CI

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build"
    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:  # Indentation fixed here
      - name: Test
        run: echo "Test"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: echo "Deploy"
