name: CI

on:
  schedule:
    - cron: '22 18 * * *'
  # push:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build"
    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:  # Indentação corrigida
      - name: Test
        uses: giuzucca/teste@main
        with:
          a: 1
          b: 2
        
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy
        run: echo "Deploy"
