name: CI

on:
  schedule:
    - cron: '22 18 * * *'
  push:
    branches: [main]  
  workflow_dispatch:  

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build"
    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        uses: Giuzucca/Teste@main
        with:
          a: 1
          b: 2
      - name: File
        run: echo "test" > test.txt

      - name: Download
        uses: actions/upload-artifact@v4
        with:
          path: test.txt
        
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy
        run: echo "Deploy"
