name: CI

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:  # A indentação correta aqui
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build"

      - name: Test
        run: echo "Test"

      - name: Deploy
        run: echo "Deploy"
